# Generated by Django 4.2.4 on 2023-08-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_boxe_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='Area',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='box',
            name='Height',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='box',
            name='Length',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='box',
            name='Volume',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='box',
            name='width',
            field=models.FloatField(max_length=20),
        ),
    ]
