# Generated by Django 4.2.4 on 2023-08-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_box_area_alter_box_height_alter_box_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='box',
            name='Volume',
        ),
    ]
