# Generated by Django 4.2.4 on 2023-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_box_area_remove_box_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='Height',
            field=models.FloatField(blank=True, default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='box',
            name='Length',
            field=models.FloatField(blank=True, default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='box',
            name='width',
            field=models.FloatField(blank=True, default=1, max_length=20),
        ),
    ]
