# Generated by Django 4.2.4 on 2023-08-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_box_height_alter_box_length_alter_box_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='Area',
            field=models.FloatField(blank=True, default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='box',
            name='Volume',
            field=models.FloatField(blank=True, default=1, max_length=20),
        ),
    ]
