# Generated by Django 4.2.4 on 2023-08-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_box_ceated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='Ceated',
        ),
    ]
